import { User } from "./atoms";

export const users: User[] = [
  {
    id: 'u1',
    email: 'admin@benvily.com',
    name: 'John Doe',
    phone: '9988667755',
    bookings: 3,
    createdAt: '2025-01-01',
    status: "A",
    salons: 1,
    services: 5,
    styles: 10,
    gst: "27ABCDE1234F1Z5"
  },
  {
    id: 'u2',
    email: 'admin@example.com',
    name: 'Raj',
    phone: '9867564534',
    bookings: 0,
    createdAt: '2020-01-01',
    status: "A",
    salons: 1,
    services: 4,
    styles: 8,
    gst: "26ABCDE1234F1Z5"
  },
    {
      id: 'u3',
      name: "Kumar",
      email: "vinay@example.com",
      status: "A",
      bookings: 5,
      phone: '6787564534',
      createdAt: '1998-01-01',
      salons: 1,
    services: 9,
    styles: 16,
    gst: "66ABCDE1234F1Z5"
    },
    {
      id: 'u4',
      name: "Rahul Sharma",
      email: "rahul@example.com",
      status: "P",
      bookings: 30,
      phone: '7656454323',
      createdAt: '1992-01-01',
      salons: 6,
    services: 3,
    styles: 5,
    gst: "87GBCDE1234F1Z5"
    },
    {
      id: 'u5',
      name: "Neha Reddy",
      email: "sneha@example.com",
      status: "R",
      bookings: 40,
      phone: '9834546576',
      createdAt: '2000-01-01',
      salons: 2,
    services: 7,
    styles: 15,
    gst: "87JHCDE1234F1Z5"
    },
    {
      id: 'u6',
      name: "Arjun Patel",
      email: "arjun@example.com",
      status: "A",
      bookings: 8,
      phone: '6745095687',
      createdAt: '2002-01-01',
      salons: 2,
    services: 3,
    styles: 3,
    gst: "76ALCDE1234F1Z5"
    },


];

export const services: Service[] = [
  {
    id: 's1',
    name: 'Haircut',
    description: 'Professional haircut tailored to your style',
    duration: 30,
    basePrice: 300,
    availableGenders: ['Male', 'Female', 'Unisex'],
    image: "/style-classic-fade.jpg"
  },
  {
    id: 's2',
    name: 'Coloring',
    description: 'Expert hair coloring and dyeing services',
    duration: 90,
    basePrice: 250,
    availableGenders: ['Female', 'Unisex'],
    image: "/style-blonde.png"
  },
  {
    id: 's3',
    name: 'Styling',
    description: 'Professional styling for special occasions',
    duration: 60,
    basePrice: 350,
    availableGenders: ['Female', 'Unisex'],
    image: "/style-waves.jpg"
  },
  {
    id: 's4',
    name: 'Massage',
    description: 'Relaxing massage therapy',
    duration: 60,
    basePrice: 350,
    availableGenders: ['Male', 'Female', 'Unisex'],
    image: "/chair-massage-ladies.jpg"
  },
  {
    id: 's5',
    name: 'Facial',
    description: 'Rejuvenating facial treatments',
    duration: 45,
    basePrice: 300,
    availableGenders: ['Female', 'Unisex'],
    image: "/classic-facial.jpeg"
  },
  {
    id: 's6',
    name: 'Waxing',
    description: 'Professional waxing services',
    duration: 30,
    basePrice: 250,
    availableGenders: ['Female', 'Unisex'],
    image: "/soft-wax.jpeg"
  },
];

export const styles: Style[] = [
  {
    id: 'st1',
    name: 'Classic Fade',
    description: 'Timeless fade with clean lines',
    image: '/style-classic-fade.jpg',
    serviceId: 's1',
    price: 450,
    availableGenders: ['Male', 'Unisex'],
    rating: 4.8,
    reviews: 245,
  },
  {
    id: 'st2',
    name: 'Textured Top',
    description: 'Modern textured cut with volume',
    image: '/style-textured.jpg',
    serviceId: 's1',
    price: 500,
    availableGenders: ['Male', 'Unisex'],
    rating: 4.7,
    reviews: 205,
  },
  {
    id: 'st3',
    name: 'Luxury Bob',
    description: 'Elegant bob cut for sophistication',
    image: '/style-bob.jpg',
    serviceId: 's1',
    price: 550,
    availableGenders: ['Female', 'Unisex'],
    rating: 4.0,
    reviews: 145,
  },
  {
    id: 'st4',
    name: 'Balayage',
    description: 'Sun-kissed natural looking highlights',
    image: '/style-balayage.jpg',
    serviceId: 's2',
    price: 320,
    availableGenders: ['Female', 'Unisex'],
    rating: 4.1,
    reviews: 145,
  },
  {
    id: 'st5',
    name: 'Blonde Highlights',
    description: 'Radiant blonde highlights',
    image: '/style-blonde.png',
    serviceId: 's2',
    price: 200,
    availableGenders: ['Female', 'Unisex'],
    rating: 3.9,
    reviews: 25,
  },
  {
    id: 'st6',
    name: 'Bridal Styling',
    description: 'Elegant styling for your special day',
    image: '/style-bridal.png',
    serviceId: 's3',
    price: 850,
    availableGenders: ['Female', 'Unisex'],
    rating: 4.7,
    reviews: 247,
  },
  {
    id: 'st7',
    name: 'Evening Waves',
    description: 'Glamorous wavy styling for events',
    image: '/style-waves.jpg',
    serviceId: 's3',
    price: 550,
    availableGenders: ['Female', 'Unisex'],
    rating: 4.2,
    reviews: 285,
  },
  {
    id: 'st8',
    name: 'Chair Massage',
    description: 'chair-massage-gents',
    image: '/chair-massage-gents.webp',
    serviceId: 's4',
    price: 150,
    availableGenders: ['Male'],
    rating: 4.8,
    reviews: 225,
  },
    {
    id: 'st9',
    name: 'Chair Massage',
    description: 'chair massage ladies',
    image: '/chair-massage-ladies.jpg',
    serviceId: 's4',
    price: 210,
    availableGenders: ['Female'],
    rating: 4.4,
    reviews: 225,
  },
     {
    id: 'st10',
    name: 'Reflexology Massage',
    description: 'reflexology massage',
    image: '/reflexology-massage.jpeg',
    serviceId: 's4',
    price: 140,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 4.9,
    reviews: 125,
  },
     {
    id: 'st11',
    name: 'Massage',
    description: 'massage',
    image: '/massage.webp',
    serviceId: 's4',
    price: 150,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 4.3,
    reviews: 110,
  },
  {
    id: 'st12',
    name: 'coloring men hair',
    description: 'coloring men hair',
    image: '/coloring-men-hair.png',
    serviceId: 's2',
    price: 150,
    availableGenders: [ 'Male'],
    rating: 4.3,
    reviews: 110,
  },
   {
    id: 'st13',
    name: 'coloring-hair',
    description: 'coloring-hair',
    image: '/coloring-hair.jpg',
    serviceId: 's2',
    price: 250,
    availableGenders: ['Female', 'Unisex'],
    rating: 4.1,
    reviews: 380,
  },
  {
    id: 'st14',
    name: 'soft-wax',
    description: 'soft-wax',
    image: '/soft-wax.jpeg',
    serviceId: 's6',
    price: 150,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 3.9,
    reviews: 180,
  },
    {
    id: 'st15',
    name: 'hard-wax',
    description: 'hard-wax',
    image: '/hard-wax.webp',
    serviceId: 's6',
    price: 150,
    availableGenders: ['Female', 'Unisex'],
    rating: 3.8,
    reviews: 180,
  },
 {
    id: 'st16',
    name: 'Classic Facial',
    description: 'Classic facial',
    image: '/classic-facial.jpeg',
    serviceId: 's5',
    price: 150,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 3.6,
    reviews: 180,
  },
   {
    id: 'st17',
    name: 'Hydrating Facial',
    description: 'Hydrating facial',
    image: '/hydrating-facial.jpeg',
    serviceId: 's5',
    price: 180,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 4.6,
    reviews: 200,
  },
  {
    id: 'st18',
    name: 'Anti Aging Facial',
    description: 'Anti aging facial',
    image: '/anti-aging-facial.jpeg',
    serviceId: 's5',
    price: 180,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 4.6,
    reviews: 200,
  },
   {
        id: 'st19',
        name: 'Wolf Cut',
        description: 'Elegant bob cut for sophistication',
        image: '/service-1.jpg',
        serviceId: 's1',
        price: 650,
        availableGenders: ['Unisex'],
        rating: 4.0,
        reviews: 145,
      },
];

export const salons: Salon[] = [
  {
    id: 'sal1',
    name: 'Luxe Salon & Spa',
    location: '123 Main Street, Downtown',
    image: '/salon-luxe.jpg',
    rating: 4.8,
    reviews: 245,
    openHours: { open: '09:00', close: '20:00' },
    services: ['s1', 's2', 's3', 's4', 's5', 's6'],
  },
  {
    id: 'sal2',
    name: 'Elite Barber Club',
    location: '456 Oak Avenue, Midtown',
    image: '/salon-elite.jpg',
    rating: 4.7,
    reviews: 189,
    openHours: { open: '10:00', close: '19:00' },
    services: ['s1', 's4'],
  },
  {
    id: 'sal3',
    name: 'Prestige Beauty Studio',
    location: '789 Park Road, Uptown',
    image: '/salon-prestige.jpg',
    rating: 4.9,
    reviews: 312,
    openHours: { open: '09:30', close: '20:30' },
    services: ['s1', 's2', 's3', 's5', 's6'],
  },
  {
    id: 'sal4',
    name: 'Refined Hair Design',
    location: '321 River Lane, North Side',
    image: '/salon-refined.jpg',
    rating: 4.6,
    reviews: 156,
    openHours: { open: '10:00', close: '18:00' },
    services: ['s1', 's2', 's3'],
  },
];

export const stylists: Stylist[] = [
  {
    id: 'sty1',
    name: 'Marcus Johnson',
    specializations: ['Haircut'],
    image: "",
    rating: 4.9,
    reviews: 87,
    salonId: 'sal1',
    genderSpecialization: 'Male',
  },
  {
    id: 'sty2',
    name: 'Sarah Chen',
    specializations: ['Coloring', 'Styling'],
    image: '',
    rating: 5.0,
    reviews: 124,
    salonId: 'sal1',
    genderSpecialization: 'Female',
  },
  {
    id: 'sty3',
    name: 'David Smith',
    specializations: ['Haircut', 'Styling'],
    image: '',
    rating: 4.7,
    reviews: 65,
    salonId: 'sal2',
    genderSpecialization: 'Male',
  },
  {
    id: 'sty4',
    name: 'Emma Wilson',
    specializations: ['Styling', 'Coloring'],
    image: '',
    rating: 4.8,
    reviews: 156,
    salonId: 'sal3',
    genderSpecialization: 'Female',
  },
  {
    id: 'sty5',
    name: 'James Rodriguez',
    specializations: ['Haircut'],
    image: '',
    rating: 4.6,
    reviews: 43,
    salonId: 'sal2',
    genderSpecialization: 'Male',
  },
  {
    id: 'sty6',
    name: 'Olivia Martinez',
    specializations: ['Facial', 'Massage'],
    image: '',
    rating: 4.9,
    reviews: 98,
    salonId: 'sal1',
    genderSpecialization: 'Female',
  },
];